services:
  - type: web
    name: freefire-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python TcPBoT-PARAHEX.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
